const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const html = fs.readFileSync('index.html', 'utf8');
const scripts = []; let m; const re = /<script(?![^>]*src)[^>]*>([\s\S]*?)<\/script>/gi;
while ((m = re.exec(html)) !== null) scripts.push(m[1]);
const testCode = String.raw`
(async function(){
  S = defaultState(); let saves = 0; saveAsync = async () => { saves++; }; save = () => {};
  renderView = function(){}; alert = function(message){ throw new Error(String(message)); }; confirm = () => true; window.confirm = confirm;
  ui.cleanupReview = { proposals: [], projectId: 'p1', incomingFeatures: [], rawAnalysisJson: '', mode: 'import-cleanup', summary: '', openQuestions: [], visible: true, activeRunId: '', workbenchStatusFilter: 'all', workbenchSelectedCaseIds: [], statusPoolSelectedCaseIds: [] };
  S.projects.push({ id: 'p1', title: 'P1' }, { id: 'p2', title: 'P2' });
  S.features.push(ensureFeatureDefaults({ id:'f1', projectId:'p1', title:'One', description:'D1', category:'Sonstiges', priority:'hoch', pool:'planned', status:'planned', reviewStatus:'reviewed', updatedAt:'f1-base', trello:{ cardId:'keep' } }));
  S.features.push(ensureFeatureDefaults({ id:'f2', projectId:'p1', title:'Two', description:'D2', category:'Sonstiges', priority:'mittel', pool:'planned', status:'selected-for-sprint', reviewStatus:'needs-review', updatedAt:'f2-base' }));
  const run = createCleanupWorkbenchRunFromReview({summary:'s'}, [
    {type:'match-existing', targetFeatureId:'f1', resolvedTitle:'One', confidence:'hoch'},
    {type:'update-existing', targetFeatureId:'f2', resolvedTitle:'Two', confidence:'mittel'}
  ], []);
  hydrateCleanupReviewFromWorkbenchRun(run); const ids = run.result.proposals.map(p => p.caseId);
  const featureBeforeReview = JSON.stringify(S.features), rootsBefore = JSON.stringify({queues:S.mainChatQueue, trash:S.trash, deletedIds:S.deletedIds});
  saves=0; await applyCleanupWorkbenchReviewStatusBatch([ids[0]], 'reviewed');
  assert.strictEqual(getActiveCleanupWorkbenchRun().reviewState.cases[ids[0]].status, 'reviewed'); assert.strictEqual(saves,1); assert.strictEqual(JSON.stringify(S.features), featureBeforeReview); assert.strictEqual(JSON.stringify({queues:S.mainChatQueue,trash:S.trash,deletedIds:S.deletedIds}),rootsBefore);
  await applyCleanupWorkbenchReviewStatusBatch([ids[0]], 'open'); assert.strictEqual(getActiveCleanupWorkbenchRun().reviewState.cases[ids[0]].status,'open');
  await applyCleanupWorkbenchReviewStatusBatch([ids[0]], 'rejected'); assert.strictEqual(getActiveCleanupWorkbenchRun().reviewState.cases[ids[0]].status,'rejected');
  await applyCleanupWorkbenchReviewStatusBatch([ids[0]], 'deferred'); assert.strictEqual(getActiveCleanupWorkbenchRun().reviewState.cases[ids[0]].status,'deferred');
  await applyCleanupWorkbenchReviewStatusBatch(ids, 'reviewed'); assert.strictEqual(getCleanupWorkbenchProgress(getActiveCleanupWorkbenchRun()).reviewed,2);
  ui.cleanupReview.workbenchSelectedCaseIds=ids.slice(); clearCleanupWorkbenchReviewSelection(); assert.deepStrictEqual(ui.cleanupReview.workbenchSelectedCaseIds,[]);
  const completed=getActiveCleanupWorkbenchRun(); completed.reviewState.runStatus='completed'; upsertCleanupWorkbenchRun(completed); let blocked=false; try{await applyCleanupWorkbenchReviewStatusBatch([ids[0]],'open')}catch(e){blocked=true} assert(blocked); completed.reviewState.runStatus='active'; upsertCleanupWorkbenchRun(completed); hydrateCleanupReviewFromWorkbenchRun(completed);
  const payload={schemaVersion:CLEANUP_STATUS_POOL_DECISION_SCHEMA_VERSION,projectId:'p1',runId:completed.id,decisions:ids.map((caseId,i)=>({caseId,featureId:'f'+(i+1),decision:'confirm-implemented',fromPool:'planned',fromStatus:i?'selected-for-sprint':'planned',toPool:'implemented',toStatus:'confirmed',summary:'Evidence reviewed'}))};
  const decisionRun=normalizeCleanupWorkbenchRunRecord(findCleanupWorkbenchRun(completed.id)); const decisionCase=decisionRun.reviewState.cases[ids[0]];
  const mainDecision=(decision)=>normalizeCleanupWorkbenchMainChatDecision({schemaVersion:CLEANUP_MAINCHAT_DECISION_SCHEMA_VERSION,projectId:'p1',caseId:ids[0],featureId:'f1',decision,summary:'',proposedTitle:'',proposedDescription:'',proposedCategory:'',proposedStatus:'',proposedPool:'',canonicalFeatureId:'',splitProposal:null,openQuestion:'',validatedAt:new Date().toISOString()},decisionRun,ids[0],'f1');
  for (const decision of ['update-existing','promote-existing','split-feature','create-implemented-feature','mark-duplicate-candidate']) { decisionCase.mainChatDecision=mainDecision(decision); upsertCleanupWorkbenchRun(decisionRun); hydrateCleanupReviewFromWorkbenchRun(decisionRun); assert(!validateCleanupStatusPoolDecisionPayload(Object.assign({},payload,{decisions:[payload.decisions[0]]})).valid,decision+' blocks import'); }
  for (const decision of CLEANUP_MAINCHAT_MUTATION_FREE_DECISIONS) { decisionCase.mainChatDecision=mainDecision(decision); upsertCleanupWorkbenchRun(decisionRun); hydrateCleanupReviewFromWorkbenchRun(decisionRun); assert(validateCleanupStatusPoolDecisionPayload(Object.assign({},payload,{decisions:[payload.decisions[0]]})).valid,decision+' remains mutation-free'); }
  decisionCase.mainChatDecision=null; upsertCleanupWorkbenchRun(decisionRun); hydrateCleanupReviewFromWorkbenchRun(decisionRun);
  S.features.find(f=>f.id==='f1').trashedAt='2026-08-14T00:00:00.000Z'; assert(!validateCleanupStatusPoolDecisionPayload(Object.assign({},payload,{decisions:[payload.decisions[0]]})).valid,'trashed feature blocks decision import'); assert(!getCleanupStatusPoolEligibility(getActiveCleanupWorkbenchRun(),ids[0]).eligible,'trashed feature blocks eligibility'); S.features.find(f=>f.id==='f1').trashedAt='';
  assert(validateCleanupStatusPoolDecisionPayload(payload).valid); saves=0; const statusPreview=await persistCleanupStatusPoolDecisions(payload); assert.strictEqual(saves,1); assert.strictEqual(S.features[0].pool,'planned','decision import is mutation-free');
  const noOpBefore=JSON.stringify(S); saves=0; await persistCleanupStatusPoolDecisions(payload); assert.strictEqual(saves,0,'identical reimport does not save'); assert.strictEqual(JSON.stringify(S),noOpBefore,'identical reimport is byte-identical');
  const changedPayload=JSON.parse(JSON.stringify(payload)); changedPayload.decisions[0].summary='Updated evidence summary'; saves=0; await persistCleanupStatusPoolDecisions(changedPayload); assert.strictEqual(saves,1,'changed decision saves exactly once'); payload.decisions[0].summary='Updated evidence summary';
  let liveStatusPreview=buildCleanupStatusPoolPreview(getActiveCleanupWorkbenchRun()); liveStatusPreview.selectedCaseIds=[ids[0]]; const preTrashBatch=buildCleanupStatusPoolTransitionBatch(liveStatusPreview); assert(preTrashBatch.valid); S.features.find(f=>f.id==='f1').trashedAt='2026-08-14T00:00:00.000Z'; assert(!getCleanupStatusPoolEligibility(getActiveCleanupWorkbenchRun(),ids[0]).eligible,'trash after import blocks eligibility'); assert(!buildCleanupStatusPoolTransitionBatch(liveStatusPreview).valid,'trash after import blocks batch'); const trashedBeforeCommit=JSON.stringify(S); saves=0; await assert.rejects(()=>commitCleanupMainChatUpdateBatch(liveStatusPreview,preTrashBatch),/Eligibility/); assert.strictEqual(saves,0); assert.strictEqual(JSON.stringify(S),trashedBeforeCommit,'blocked trashed commit leaves pool/status/application untouched'); assert.strictEqual(getActiveCleanupWorkbenchRun().reviewState.cases[ids[0]].mainChatApplication,null); assert.strictEqual(S.features.find(f=>f.id==='f1').pool,'planned'); S.features.find(f=>f.id==='f1').trashedAt='';
  const refreshedPreview=buildCleanupStatusPoolPreview(getActiveCleanupWorkbenchRun()); ui.cleanupReview.statusPoolDecisionPreview=refreshedPreview; toggleCleanupStatusPoolSelection(ids[0],true); toggleCleanupStatusPoolSelection(ids[1],true); reviewCleanupStatusPoolSelection(); assert(ui.cleanupReview.statusPoolDecisionPreview.pendingBatch && Object.isFrozen(ui.cleanupReview.statusPoolDecisionPreview.pendingBatch)); toggleCleanupStatusPoolSelection(ids[1],false); assert.strictEqual(ui.cleanupReview.statusPoolDecisionPreview.pendingBatch,null,'selection change invalidates frozen diff'); reviewCleanupStatusPoolSelection(); const samePending=ui.cleanupReview.statusPoolDecisionPreview.pendingBatch; toggleCleanupStatusPoolSelection(ids[0],true); assert.strictEqual(ui.cleanupReview.statusPoolDecisionPreview.pendingBatch,samePending,'identical selection state retains pending diff'); ui.cleanupReview.statusPoolDecisionPreview.pendingBatch=null; assert.strictEqual(S.features[0].pool,'planned','diff cancel is mutation-free');
  refreshedPreview.selectedCaseIds=ids.slice(); const batch=buildCleanupStatusPoolTransitionBatch(refreshedPreview); assert(batch.valid,batch.errors.join('\n')); assert(Object.isFrozen(batch));
  const frozen=JSON.stringify(batch); statusPreview.selectedCaseIds=[]; assert.strictEqual(JSON.stringify(batch),frozen);
  const beforeCommit=JSON.parse(JSON.stringify(S)); saves=0; await commitCleanupMainChatUpdateBatch(statusPreview,batch); assert.strictEqual(saves,1);
  assert.strictEqual(S.features[0].pool,'implemented'); assert.strictEqual(S.features[0].status,'confirmed'); assert.strictEqual(S.features[1].pool,'implemented'); assert.strictEqual(S.features[1].status,'confirmed');
  ['title','description','category','priority','reviewStatus','trello'].forEach(field=>assert.deepStrictEqual(S.features[0][field],beforeCommit.features[0][field],field+' protected'));
  const applied=getActiveCleanupWorkbenchRun(); ids.forEach(id=>{const app=applied.reviewState.cases[id].mainChatApplication; assert.strictEqual(app.applicationType,'status-pool-transition'); assert.deepStrictEqual(app.changedFields.map(c=>c.field),['pool','status']);});
  assert.strictEqual(normalizeCleanupWorkbenchMainChatApplication({status:'applied',caseId:'x',featureId:'f1',appliedAt:new Date().toISOString(),batchId:'b',changedFields:[{field:'title',oldValue:'a',newValue:'b'}]},'x','f1').applicationType,'update-existing');
  const transitionApp=(changes)=>normalizeCleanupWorkbenchMainChatApplication({status:'applied',applicationType:'status-pool-transition',caseId:'x',featureId:'f1',appliedAt:new Date().toISOString(),batchId:'b',changedFields:changes},'x','f1');
  const pool={field:'pool',oldValue:'planned',newValue:'implemented'}, planned={field:'status',oldValue:'planned',newValue:'confirmed'}, selected={field:'status',oldValue:'selected-for-sprint',newValue:'confirmed'};
  assert.strictEqual(transitionApp([pool]).status,'invalid'); assert.strictEqual(transitionApp([planned]).status,'invalid'); assert.strictEqual(transitionApp([pool,planned]).status,'applied'); assert.strictEqual(transitionApp([pool,selected]).status,'applied');
  assert.strictEqual(transitionApp([pool,pool]).status,'invalid'); assert.strictEqual(transitionApp([pool,planned,{field:'title',oldValue:'a',newValue:'b'}]).status,'invalid'); assert.strictEqual(transitionApp([{field:'pool',oldValue:'planned',newValue:'confirmed'},planned]).status,'invalid'); assert.strictEqual(transitionApp([pool,{field:'status',oldValue:'idea',newValue:'confirmed'}]).status,'invalid');
  assert.strictEqual(normalizeCleanupWorkbenchMainChatApplication({status:'applied',applicationType:'unknown',caseId:'x',featureId:'f1',appliedAt:new Date().toISOString(),batchId:'b',changedFields:[{field:'pool',oldValue:'planned',newValue:'implemented'}]},'x','f1').status,'invalid');
  const bad=Object.assign({},payload,{schemaVersion:'bad'}); assert(!validateCleanupStatusPoolDecisionPayload(bad).valid);
  assert(!isAllowedCleanupStatusPoolTransition('planned','idea','implemented','confirmed')); assert(!isAllowedCleanupStatusPoolTransition('implemented','detected','implemented','confirmed')); assert(!isAllowedCleanupStatusPoolTransition('planned','planned','implemented','detected'));
  // Save failure rolls the whole review batch back.
  const rollbackRun=getActiveCleanupWorkbenchRun(); rollbackRun.reviewState.cases[ids[0]].mainChatApplication=null; upsertCleanupWorkbenchRun(rollbackRun); hydrateCleanupReviewFromWorkbenchRun(rollbackRun); const rollbackBefore=JSON.stringify(S); saveAsync=async()=>{throw new Error('save fail')}; alert=()=>{}; const ok=await applyCleanupWorkbenchReviewStatusBatch([ids[0]],'open'); assert.strictEqual(ok,false); assert.strictEqual(JSON.stringify(S),rollbackBefore);

  // A raw legacy run may omit a proposal's persisted case; review must normalize only the candidate and retain exact rollback state.
  const buildLegacyState=()=>{ const state=defaultState(); state.projects.push({id:'legacy-project',title:'Legacy'}); state.features.push(ensureFeatureDefaults({id:'legacy-feature',projectId:'legacy-project',title:'Legacy Feature',pool:'planned',status:'planned'})); state.analyses.push({id:'legacy-run',type:CLEANUP_WORKBENCH_ANALYSIS_TYPE,schemaVersion:CLEANUP_WORKBENCH_SCHEMA_VERSION,projectId:'legacy-project',source:{cleanupMode:'import-cleanup'},result:{summary:'legacy',proposals:[{caseId:'legacy-case',type:'match-existing',targetFeatureId:'legacy-feature',resolvedTitle:'Legacy Feature'}],openQuestions:[]},reviewState:{runStatus:'active',cases:{}},createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}); state.analyses.push({id:'foreign-analysis',type:'foreign',payload:{keep:true}}); return state; };
  S=buildLegacyState(); ui.cleanupReview={projectId:'legacy-project',activeRunId:'legacy-run',workbenchStatusFilter:'all',workbenchSelectedCaseIds:[]}; const normalizedLegacy=getActiveCleanupWorkbenchRun(); assert.strictEqual(normalizedLegacy.reviewState.cases['legacy-case'].status,'open'); const legacyProtectedBefore=JSON.stringify({features:S.features,foreign:S.analyses[1],queue:S.mainChatQueue,trash:S.trash,deletedIds:S.deletedIds}); saves=0; saveAsync=async()=>{saves++}; assert.strictEqual(await applyCleanupWorkbenchReviewStatusBatch(['legacy-case'],'reviewed'),true); assert.strictEqual(saves,1); const persistedLegacy=S.analyses.find(a=>a.id==='legacy-run'); assert.strictEqual(persistedLegacy.reviewState.cases['legacy-case'].status,'reviewed'); assert.strictEqual(normalizeCleanupWorkbenchRunRecord(persistedLegacy).reviewState.cases['legacy-case'].status,'reviewed'); assert.strictEqual(JSON.stringify({features:S.features,foreign:S.analyses[1],queue:S.mainChatQueue,trash:S.trash,deletedIds:S.deletedIds}),legacyProtectedBefore);
  S=buildLegacyState(); ui.cleanupReview={projectId:'legacy-project',activeRunId:'legacy-run',workbenchStatusFilter:'all',workbenchSelectedCaseIds:[]}; const rawLegacyBefore=JSON.stringify(S); saveAsync=async()=>{throw new Error('legacy save fail')}; alert=()=>{}; assert.strictEqual(await applyCleanupWorkbenchReviewStatusBatch(['legacy-case'],'reviewed'),false); assert.strictEqual(JSON.stringify(S),rawLegacyBefore,'legacy save failure restores the exact raw record without partial normalization');

  // Shared Apply protection canonicalizes legacy defaults without masking protected mutations.
  const buildLegacyApplyState=()=>{ const state=defaultState(); state.projects.push({id:'apply-project',title:'Apply'}); state.features.push(ensureFeatureDefaults({id:'status-feature',projectId:'apply-project',title:'Status',pool:'planned',status:'planned',updatedAt:'status-base'}),ensureFeatureDefaults({id:'update-feature',projectId:'apply-project',title:'Update old',description:'Keep',category:'Sonstiges',pool:'implemented',status:'confirmed',updatedAt:'update-base'}),ensureFeatureDefaults({id:'legacy-app-feature',projectId:'apply-project',title:'Legacy app',pool:'implemented',status:'confirmed',updatedAt:'legacy-base'})); const at='2026-08-14T01:00:00.000Z'; state.analyses.push({id:'legacy-apply-run',type:CLEANUP_WORKBENCH_ANALYSIS_TYPE,schemaVersion:CLEANUP_WORKBENCH_SCHEMA_VERSION,projectId:'apply-project',source:{cleanupMode:'import-cleanup'},result:{summary:'legacy apply',proposals:[{caseId:'status-case',type:'match-existing',targetFeatureId:'status-feature',resolvedTitle:'Status'},{caseId:'update-case',type:'update-existing',targetFeatureId:'update-feature',resolvedTitle:'Update old'},{caseId:'legacy-app-case',type:'match-existing',targetFeatureId:'legacy-app-feature',resolvedTitle:'Legacy app'}],openQuestions:[]},reviewState:{runStatus:'active',cases:{'status-case':{status:'reviewed',updatedAt:at,mainChatDecision:null,statusPoolDecision:{schemaVersion:CLEANUP_STATUS_POOL_DECISION_SCHEMA_VERSION,projectId:'apply-project',runId:'legacy-apply-run',caseId:'status-case',featureId:'status-feature',decision:'confirm-implemented',fromPool:'planned',fromStatus:'planned',toPool:'implemented',toStatus:'confirmed',summary:'confirmed',validatedAt:at},mainChatApplication:null,dedupeDecision:null},'update-case':{status:'reviewed',updatedAt:at,mainChatDecision:{schemaVersion:CLEANUP_MAINCHAT_DECISION_SCHEMA_VERSION,projectId:'apply-project',caseId:'update-case',featureId:'update-feature',decision:'update-existing',summary:'rename',proposedTitle:'Update new',proposedDescription:'',proposedCategory:'',proposedStatus:'',proposedPool:'',canonicalFeatureId:'',splitProposal:null,openQuestion:'',validatedAt:at},mainChatApplication:null,dedupeDecision:null},'legacy-app-case':{status:'reviewed',updatedAt:at,mainChatDecision:null,mainChatApplication:{status:'applied',caseId:'legacy-app-case',featureId:'legacy-app-feature',appliedAt:at,batchId:'legacy-batch',changedFields:[{field:'title',oldValue:'Older',newValue:'Legacy app'}]},dedupeDecision:null}}},createdAt:at,updatedAt:at}); return state; };
  S=buildLegacyApplyState(); ui.cleanupReview={projectId:'apply-project',activeRunId:'legacy-apply-run',mode:'import-cleanup',workbenchStatusFilter:'all',statusPoolSelectedCaseIds:[],workbenchSelectedCaseIds:[]}; hydrateCleanupReviewFromWorkbenchRun(getActiveCleanupWorkbenchRun()); assert.strictEqual(Object.prototype.hasOwnProperty.call(S.analyses[0].reviewState.cases['update-case'],'statusPoolDecision'),false); assert.strictEqual(Object.prototype.hasOwnProperty.call(S.analyses[0].reviewState.cases['legacy-app-case'].mainChatApplication,'applicationType'),false); const mainBeforeStatus=ui.cleanupReview.mainChatDecisionPreview; assert(mainBeforeStatus.items.find(i=>i.caseId==='update-case').selectable); ui.cleanupReview.statusPoolDecisionPreview.selectedCaseIds=['status-case']; reviewCleanupStatusPoolSelection(); const legacyStatusBatch=ui.cleanupReview.statusPoolDecisionPreview.pendingBatch; const tamperedLegacy=JSON.parse(JSON.stringify(S)); tamperedLegacy.analyses[0].result.summary='forbidden'; assert(getCleanupMainChatProtectedStateDiffs(S,tamperedLegacy,legacyStatusBatch).length,'real protected run mutation remains detected'); saves=0; saveAsync=async()=>{saves++}; await confirmCleanupStatusPoolBatch(); assert.strictEqual(saves,1,'status commit plus both preview rebuilds uses one save'); const freshRun=getActiveCleanupWorkbenchRun(); assert.strictEqual(ui.cleanupReview.mainChatDecisionPreview.origin.runUpdatedAt,freshRun.updatedAt); assert(ui.cleanupReview.mainChatDecisionPreview.items.find(i=>i.caseId==='update-case').selectable,'unrelated update-existing remains selectable after rebuild'); assert(!buildCleanupStatusPoolPreview(freshRun).items.find(i=>i.caseId==='status-case').selectable,'applied status case is consumed'); assert.strictEqual(ui.cleanupReview.mainChatDecisionPreview.pendingBatch,null); assert.deepStrictEqual(ui.cleanupReview.mainChatDecisionPreview.selectedCaseIds,[]);
  ui.cleanupReview.mainChatDecisionPreview.selectedCaseIds=['update-case']; const legacyUpdateBatch=buildCleanupMainChatUpdateBatch(ui.cleanupReview.mainChatDecisionPreview); assert(legacyUpdateBatch.valid,legacyUpdateBatch.errors.join('\n')); saves=0; await commitCleanupMainChatUpdateBatch(ui.cleanupReview.mainChatDecisionPreview,legacyUpdateBatch); assert.strictEqual(saves,1,'legacy update-existing commit remains valid'); assert.strictEqual(S.features.find(f=>f.id==='update-feature').title,'Update new');
  S=buildLegacyApplyState(); ui.cleanupReview={projectId:'apply-project',activeRunId:'legacy-apply-run',mode:'import-cleanup',workbenchStatusFilter:'all',statusPoolSelectedCaseIds:[],workbenchSelectedCaseIds:[]}; hydrateCleanupReviewFromWorkbenchRun(getActiveCleanupWorkbenchRun()); ui.cleanupReview.statusPoolDecisionPreview.selectedCaseIds=['status-case']; const rollbackLegacyBatch=buildCleanupStatusPoolTransitionBatch(ui.cleanupReview.statusPoolDecisionPreview); const rawApplyBefore=JSON.stringify(S); saveAsync=async()=>{throw new Error('apply legacy save fail')}; await assert.rejects(()=>commitCleanupMainChatUpdateBatch(ui.cleanupReview.statusPoolDecisionPreview,rollbackLegacyBatch),/apply legacy save fail/); assert.strictEqual(JSON.stringify(S),rawApplyBefore,'legacy apply rollback restores exact raw state');
})().then(()=>console.log('cleanup workbench bulk review/status-pool tests OK')).catch(err=>{console.error(err);process.exit(1)});`;
const context={console,assert,process,localStorage:{getItem(){return null},setItem(){},removeItem(){}},document:{addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},getElementById(){return null},body:{classList:{toggle(){}}}},window:{},navigator:{clipboard:{writeText(){return Promise.resolve()}}},Blob:function(){},URL:{createObjectURL(){return''},revokeObjectURL(){}},alert(){},confirm(){return true},setTimeout(fn){if(typeof fn==='function')fn();return 1},clearTimeout(){},crypto:{getRandomValues(a){a[0]=123;return a}}}; context.window=context;
vm.createContext(context); const app=scripts.join('\n').replace('      init();','      // init disabled'); const combined=app.replace(/\n\s*\}\)\(\);\s*$/, '\n'+testCode+'\n    })();');
vm.runInContext(combined,context,{timeout:10000});
